version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: dating_postgres_db
    environment:
      POSTGRES_DB: dating_appdb
      POSTGRES_USER: dating_appuser
      POSTGRES_PASSWORD: dating_apppass
    ports:
      - "5432:5432"
    volumes:
      - dating_db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  dating_db_data:
